### ISSUE TITLE
Crafting upgrade breaks inventory crafting results

### ISSUE THREAD

**Issue by Fortist** [V0idWa1k3r/SmartBackpacks#35]
I had thought it was another mod but to think it was this mod instead.

Well, anyway, Any crafting recipe within my inventory crafting menu (2x2) has its results disppear after a second of putting it in.
I could still craft, but sometimes it bugs out a bit and I have to click the crafting items to get whatever I crafted.
FOR EXAMPLE. Iron block to Iron Ingots. Ingots disappear after roughly a second. Click "empty" space and receive ingots and/OR click iron block and receive ingots.

This only happens when I have a bag with the Crafting Upgrade in it, with the bag on me or holding it.
Ill probably test other upgrades.

**It is possibly a conflict -somewhere- but I havent tried troubleshooting it yet.**

**Comment by DPattee** [comment]
Same broken 'regular 2x2 crafting UI broken' issue here, but different upgrade. 

I can put, for example, stacks of planks in the 2x2 and for a brief second see a table flash in the output slot before it goes empty again. If i repeatedly click in the empty box sometimes it will flash an output icon again, and I eventually pick up a table (whether or not it was actually visible in the box at that moment).

The only upgrades I had installed in to my backpack when the issue started was the Compressing Upgrade. But since that one also does automatic crafting I expect it is the same root cause.
